version: "3.8"
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs
    restart: always
    env_file:
      - ".env"
    ports:
      - 8077:8077
  redis:
    container_name: redis
    restart: always
    image: redis:alpine
    ports:
      - 6379:6379
