// documentation of the swagger-autogen can be found here:
// https://github.com/davibaltar/swagger-autogen#building-documentation-without-starting-the-project

const swaggerAutogen = require('swagger-autogen')()


const doc = {
    swagger: "2.0",
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:8077",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ]
}

const outputFile = './src/docs/swagger_output.json'
const endpointsFiles = [
    './src/routers/user.js',
    './src/routers/db.js',
    './src/routers/meal.js',
    './src/routers/recipe.js',
    './src/routers/ingredient.js',
    './src/mongo/schema/user.js'
]


swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index')           // Your project's root file
})
